### ISSUE TITLE
Log edit

### ISSUE THREAD

**Issue by Johannes2306** [NoahCardoza/HE-REvived-Issue-Tracker#22] opened 2019-09-23 12:12 UTC
Editing logs on localhost just simply reloads the page instead of showing task progress, task itself is however initiated and can be completed via task manager.

Editing logs on remote server does not initiate any tasks regarding log edit and instead redirects you to blank `/LogEdit` page with the same error shown as in issue #21, but also adds `Error: hardware is not registered` to the end of it.

**Comment by NoahCardoza** [comment] 2019-09-23 18:09
I can't reproduce this on my end.

However, I do know that `Error: hardware is not registered` mean's there are no servers tied to your  VPC, so I am assuming it's a database issue. I know @notdls was messing around with a fix for something not too long ago.

@bobokev Are you seeing anything?

**Comment by bobokev** [comment] 2019-09-23 21:56
yes i get that error aswell

**Comment by notdls** [comment] 2019-09-24 04:38
this should be fixed now

**Closed by notdls** 2019-09-24 04:38 UTC

**Comment by Johannes2306** [comment] 2019-09-24 08:47
@notdls 
> this should be fixed now

The issue has been fixed for the local edits, but remote log edit is still broken as stated earlier.
>Editing logs on remote server does not initiate any tasks regarding log edit and instead redirects you to blank /LogEdit page with the same error shown as in issue #21, but also adds Error: hardware is not registered to the end of it.

(except that now it shows only `Error: Hardware not registered`)

**Comment by NoahCardoza** [comment] 2019-09-24 16:48
@notdls when you were messing with queries I wonder if you did it in a way that keeps the users servers by being found? Like the isNPC column is not being used correctly?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by notdls** [comment] 2019-09-24 21:20
Maybe? I thought this was fixed now though
