### ISSUE TITLE
problem with clans 

### ISSUE THREAD

**Issue by bobokev** [NoahCardoza/HE-REvived-Issue-Tracker#45] opened 2019-10-04 14:08 UTC
nothing shows for clan admin
tried to upload a file got this error https://prnt.sc/pev4rn
https://prnt.sc/pev6bv

**Comment by notdls** [comment] 2019-10-04 21:46
can't seem to reproduce that first error, but that second one has been fixed, just need a new round to regenerate the logs/web server content.

**Comment by NoahCardoza** [comment] 2019-10-04 21:55
It’s probably due to requiring the PDO DB file twice... 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by notdls** [comment] 2019-10-05 09:06
should be fixed now

**Closed by notdls** 2019-10-05 09:06 UTC
