### ISSUE TITLE
uninstall on localhost not working

### ISSUE THREAD

**Issue by bobokev** [NoahCardoza/HE-REvived-Issue-Tracker#11] opened 2019-09-19 23:11 UTC
tried uninstalling, showed it was uninstalled in logs
https://prnt.sc/p8gemm
but software on  software  page its still installed
https://prnt.sc/p8gg5d

**Comment by Johannes2306** [comment] 2019-09-19 23:41
To add to that, the task itself completes successfully, but the running process is never killed.
This is localhost specific issue, for you can still uninstall software on remote servers.

**Comment by notdls** [comment] 2019-09-20 01:19
This should be fixed now, was caused by a previous bug

**Closed by notdls** 2019-09-20 01:19 UTC
